repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.0
    hooks:
      - id: clang-format
        language: system
        args:
          - "-style=file"
          - "-i"
        entry: /usr/bin/clang-format-19
        files: \.(c|cpp|cxx|cc|h|hpp|hxx|hh)$


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
  
  - repo: local
    hooks:
      - id: check-file-naming
        name: File Naming Check
        entry: bash -c "find . -type f \( -name '*.h' -o -name '*.cpp' \) ! -path './build/*' | grep -E '[A-Z]|-' && exit 1 || exit 0"
        language: system
        types: [file]

      - id: ctest
        name: Run cpp tests
        entry: ctest --test-dir /home/devel/workspace/build/build-release/tests --progress
        language: system
        pass_filenames: false
        always_run: true
