version: '3'

services:
  develop:
    image: develop
    container_name: devel
    user: ${USER_UID}:${USER_GID}
    tty: true
    env_file:
      - .env
    build:
      context: .
      args:
      - USERNAME=devel
      - USER=devel
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
    network_mode: "host"
    volumes:
      - ${WORKSPACE}:/home/devel/workspace:rw
      - ${HOME}/.ssh:/home/devel/.ssh
      - ${HOME}/.gitconfig:/home/devel/.gitconfig
      - ${HOME}/.zshrc:/home/devel/.zshrc:ro
    entrypoint: '/bin/zsh'
