name: Manual C++ Build

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HOME: /root

    container:
      image: egorpristanskiy/ci_base:latest   # Your custom Docker image with dev tools

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Conan dependencies
        run: |
          conan install . --output-folder=build --build=missing -s build_type=Release

      - name: Configure with CMake
        run: |
          cmake --preset=conan-release

      - name: Build project
        run: |
          cmake --build --preset=conan-release -j$(nproc)

      - name: Package project
        run: |
          cmake --build --preset=conan-release --target package
