name: Docker Compose Build & Push

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: egorpristanskiy
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image with Docker Compose
        run: |
          cd docker
          docker compose build base

      - name: Tag image
        run: docker tag egorpristanskiy/ci_base egorpristanskiy/ci_base:latest

      - name: Push image
        run: docker push egorpristanskiy/ci_base:latest
